In [1]:
#Tamim Mahmud from Daffodil International University
#13/07/2025
#Day 19
#Decision Tree revised topick

üå≥ Decision Tree ‡¶ï‡ßÄ?

Decision Tree ‡¶π‡¶≤‡ßã ‡¶è‡¶ï‡¶ü‡¶ø Supervised Machine Learning Algorithm, ‡¶Ø‡ßá‡¶ü‡¶æ Classification ‡¶è‡¶¨‡¶Ç Regression‚Äî‡¶¶‡ßÅ‡¶á ‡¶ï‡¶æ‡¶ú‡ßá‡¶á ‡¶¨‡ßç‡¶Ø‡¶¨‡¶π‡¶æ‡¶∞ ‡¶ï‡¶∞‡¶æ ‡¶Ø‡¶æ‡ßü‡•§ ‡¶è‡¶ü‡¶ø ‡¶è‡¶ï‡¶ü‡¶ø ‡¶ó‡¶æ‡¶õ‡ßá‡¶∞ (Tree) ‡¶Æ‡¶§‡ßã ‡¶ó‡¶†‡¶ø‡¶§ ‡¶Ø‡ßá‡¶ñ‡¶æ‡¶®‡ßá ‡¶™‡ßç‡¶∞‡¶§‡¶ø‡¶ü‡¶ø ‡¶®‡ßã‡¶° ‡¶è‡¶ï‡¶ü‡¶ø ‡¶™‡ßç‡¶∞‡¶∂‡ßç‡¶®/‡¶∂‡¶∞‡ßç‡¶§ ‡¶•‡¶æ‡¶ï‡ßá, ‡¶è‡¶¨‡¶Ç ‡¶™‡ßç‡¶∞‡¶§‡¶ø‡¶ü‡¶ø ‡¶°‡¶æ‡¶≤ (branch) ‡¶π‡¶≤‡ßã ‡¶∏‡¶ø‡¶¶‡ßç‡¶ß‡¶æ‡¶®‡ßç‡¶§‡ßá‡¶∞ ‡¶´‡¶≤‡¶æ‡¶´‡¶≤‡•§

üìå ‡¶¨‡ßç‡¶Ø‡¶æ‡¶ñ‡ßç‡¶Ø‡¶æ:

Decision Tree ‡¶è‡¶ï‡¶ü‡¶ø if-else logic ‡¶è‡¶∞ ‡¶Æ‡¶§‡ßã ‡¶ï‡¶æ‡¶ú ‡¶ï‡¶∞‡ßá‡•§


‡¶è‡¶ü‡¶ø ‡¶°‡ßá‡¶ü‡¶æ ‡¶•‡ßá‡¶ï‡ßá ‡¶è‡¶Æ‡¶®‡¶≠‡¶æ‡¶¨‡ßá ‡¶∂‡¶∞‡ßç‡¶§ ‡¶§‡ßà‡¶∞‡¶ø ‡¶ï‡¶∞‡ßá ‡¶Ø‡¶æ‡¶§‡ßá ‡¶∏‡¶∞‡ßç‡¶¨‡ßã‡¶ö‡ßç‡¶ö ‡¶∏‡¶†‡¶ø‡¶ï‡¶≠‡¶æ‡¶¨‡ßá prediction ‡¶ï‡¶∞‡¶æ ‡¶Ø‡¶æ‡ßü‡•§


Root Node ‚Üí ‡¶™‡ßç‡¶∞‡¶•‡¶Æ ‡¶™‡ßç‡¶∞‡¶∂‡ßç‡¶®


Leaf Node ‚Üí ‡¶ö‡ßÇ‡ßú‡¶æ‡¶®‡ßç‡¶§ ‡¶∏‡¶ø‡¶¶‡ßç‡¶ß‡¶æ‡¶®‡ßç‡¶§ (Yes/No)

In [2]:
import pandas as pd
df=pd.read_csv('salaries.csv')
df

       company                  job     degree  salary_more_then_100k
0       google      sales executive  bachelors                      0
1       google      sales executive    masters                      0
2       google     business manager  bachelors                      1
3       google     business manager    masters                      1
4       google  computer programmer  bachelors                      0
5       google  computer programmer    masters                      1
6   abc pharma      sales executive    masters                      0
7   abc pharma  computer programmer  bachelors                      0
8   abc pharma     business manager  bachelors                      0
9   abc pharma     business manager    masters                      1
10    facebook      sales executive  bachelors                      1
11    facebook      sales executive    masters                      1
12    facebook     business manager  bachelors                      1
13    facebook     business manager    masters                      1
14    facebook  computer programmer  bachelors                      1
15    facebook  computer programmer    masters                      1

In [3]:
X=df[['company','job','degree']]
y=df['salary_more_then_100k']
X

       company                  job     degree
0       google      sales executive  bachelors
1       google      sales executive    masters
2       google     business manager  bachelors
3       google     business manager    masters
4       google  computer programmer  bachelors
5       google  computer programmer    masters
6   abc pharma      sales executive    masters
7   abc pharma  computer programmer  bachelors
8   abc pharma     business manager  bachelors
9   abc pharma     business manager    masters
10    facebook      sales executive  bachelors
11    facebook      sales executive    masters
12    facebook     business manager  bachelors
13    facebook     business manager    masters
14    facebook  computer programmer  bachelors
15    facebook  computer programmer    masters

In [7]:
from sklearn.preprocessing import LabelEncoder
le_company=LabelEncoder()
le_degree=LabelEncoder()
le_job=LabelEncoder()

df['Company_n']=le_company.fit_transform(df['company'])
df['Job_n']=le_job.fit_transform(df['job'])
df['Degree_n']=le_degree.fit_transform(df['degree'])


df

,company,job,degree,salary_more_then_100k,Company_n,Job_n,Degree_n
0,google,sales executive,bachelors,0,2,2,0
1,google,sales executive,masters,0,2,2,1
2,google,business manager,bachelors,1,2,0,0
3,google,business manager,masters,1,2,0,1
4,google,computer programmer,bachelors,0,2,1,0
5,google,computer programmer,masters,1,2,1,1
6,abc pharma,sales executive,masters,0,0,2,1
7,abc pharma,computer programmer,bachelors,0,0,1,0
8,abc pharma,business manager,bachelors,0,0,0,0
9,abc pharma,business manager,masters,1,0,0,1
10,facebook,sales executive,bachelors,1,1,2,0
11,facebook,sales executive,masters,1,1,2,1
12,facebook,business manager,bachelors,1,1,0,0
13,facebook,business manager,masters,1,1,0,1
14,facebook,computer programmer,bachelors,1,1,1,0
15,facebook,computer programmer,masters,1,1,1,1

In [8]:
n=df.drop(['company','degree','job'],axis='columns')
n

    salary_more_then_100k  Company_n  Job_n  Degree_n
0                       0          2      2         0
1                       0          2      2         1
2                       1          2      0         0
3                       1          2      0         1
4                       0          2      1         0
5                       1          2      1         1
6                       0          0      2         1
7                       0          0      1         0
8                       0          0      0         0
9                       1          0      0         1
10                      1          1      2         0
11                      1          1      2         1
12                      1          1      0         0
13                      1          1      0         1
14                      1          1      1         0
15                      1          1      1         1

In [16]:
print(le_company.classes_)
print(le_job.classes_)
print(le_degree.classes_)

['abc pharma' 'facebook' 'google']
['business manager' 'computer programmer' 'sales executive']
['bachelors' 'masters']

In [21]:
m=n.drop(['salary_more_then_100k'],axis='columns')
m

    Company_n  Job_n  Degree_n
0           2      2         0
1           2      2         1
2           2      0         0
3           2      0         1
4           2      1         0
5           2      1         1
6           0      2         1
7           0      1         0
8           0      0         0
9           0      0         1
10          1      2         0
11          1      2         1
12          1      0         0
13          1      0         1
14          1      1         0
15          1      1         1

In [22]:
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier()
model.fit(m,y)

DecisionTreeClassifier()

In [23]:
model.predict([[2,2,0]])

C:\Users\HP\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([0], dtype=int64)

In [24]:
model.predict([[2,0,0]])

C:\Users\HP\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([1], dtype=int64)

In [25]:
df=pd.read_csv('titanic.csv')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [26]:
df.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [34]:
X=df[['Pclass','Sex','Age','Fare']]
y=df['Survived']

from sklearn.preprocessing import LabelEncoder
le_pclass=LabelEncoder()
le_sex=LabelEncoder()
le_age=LabelEncoder()
le_fare=LabelEncoder()

X['Pclass_n']=le_pclass.fit_transform(X['Pclass'])
X['Sex_n']=le_sex.fit_transform(X['Sex'])
X['Age_n']=le_age.fit_transform(X['Age'])
X['Fare_n']=le_fare.fit_transform(X['Fare'])
X

C:\Users\HP\AppData\Local\Temp\ipykernel_14844\2318392269.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['Pclass_n']=le_pclass.fit_transform(X['Pclass'])
C:\Users\HP\AppData\Local\Temp\ipykernel_14844\2318392269.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['Sex_n']=le_sex.fit_transform(X['Sex'])
C:\Users\HP\AppData\Local\Temp\ipykernel_14844\2318392269.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['Age_n']=le_age.fit_transform(X['Age'])
C:\Users\HP\AppData\Local\Temp\ipykernel_14844\2318392269.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['Fare_n']=le_fare.fit_transform(X['Fare'])

     Pclass     Sex   Age     Fare  Pclass_n  Sex_n  Age_n  Fare_n
0         3    male  22.0   7.2500         2      1     28      18
1         1  female  38.0  71.2833         0      0     51     207
2         3  female  26.0   7.9250         2      0     34      41
3         1  female  35.0  53.1000         0      0     47     189
4         3    male  35.0   8.0500         2      1     47      43
..      ...     ...   ...      ...       ...    ...    ...     ...
886       2    male  27.0  13.0000         1      1     35      85
887       1  female  19.0  30.0000         0      0     24     153
888       3  female   NaN  23.4500         2      0     88     131
889       1    male  26.0  30.0000         0      1     34     153
890       3    male  32.0   7.7500         2      1     42      30

[891 rows x 8 columns]

In [35]:
n=X.drop(['Pclass','Sex','Age','Fare'],axis='columns')
n

     Pclass_n  Sex_n  Age_n  Fare_n
0           2      1     28      18
1           0      0     51     207
2           2      0     34      41
3           0      0     47     189
4           2      1     47      43
..        ...    ...    ...     ...
886         1      1     35      85
887         0      0     24     153
888         2      0     88     131
889         0      1     34     153
890         2      1     42      30

[891 rows x 4 columns]

In [36]:
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier()
model.fit(n,y)

DecisionTreeClassifier()

In [37]:
model.predict([[2,1,28,18]])

C:\Users\HP\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([0], dtype=int64)

In [38]:
model.predict([[0,0,51,207]])

C:\Users\HP\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([1], dtype=int64)

In [45]:
#Decision Tree Regression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.tree import DecisionTreeRegressor
from sklearn.datasets import fetch_california_housing

data=fetch_california_housing()

X=data.data
y=data.target

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

model=DecisionTreeRegressor()
model.fit(X_train,y_train)

y_pred=model.predict(X_test)

print("MSE:",mean_squared_error(y_test,y_pred))
print("r2-score:",r2_score(y_test,y_pred))

MSE: 0.5026301043404796
r2-score: 0.6164326460772476

In [46]:
#Alhamdulillah Decision Tree revised complete